[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rebalancer = "H5sewgM4P61yo75GtnbsVcevhEAVKpoRxJjsHWXoNYV7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/recursive/rebalancer/.keys/admin.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
